### ISSUE TITLE
SluggedBehavior broke model baking

### ISSUE THREAD

**Issue by TamiasSibiricus** [dereuromark/cakephp-tools#167]
When i try to bake model for plugin i get fatal error from SluggedBehavior. I have table with same name at default connection, but this behavior does not loaded in this table.

```
root@vagrant-ubuntu-trusty-64:/vagrant/supplier# bin/cake bake model Tags -c my_connection --plugin MyPlugin

Welcome to CakePHP v3.2.6 Console
---------------------------------------------------------------
App : src
Path: /vagrant/supplier/src/
PHP : 5.5.32-1+deb.sury.org~trusty+1
---------------------------------------------------------------
One moment while associations are detected.
PHP Fatal error:  Class 'Tools\Model\Behavior\Exception' not found in /vagrant/supplier/vendor/dereuromark/cakephp-tools/src/Model/Behavior/SluggedBehavior.php on line 133
PHP Stack trace:
PHP   1. {main}() /vagrant/supplier/bin/cake.php:0
PHP   2. Cake\Console\ShellDispatcher::run() /vagrant/supplier/bin/cake.php:33
PHP   3. Cake\Console\ShellDispatcher->dispatch() /vagrant/supplier/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php:127
PHP   4. Cake\Console\ShellDispatcher->_dispatch() /vagrant/supplier/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php:181
PHP   5. Cake\Console\Shell->runCommand() /vagrant/supplier/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php:217
PHP   6. Cake\Console\Shell->runCommand() /vagrant/supplier/vendor/cakephp/cakephp/src/Console/Shell.php:450
PHP   7. call_user_func_array:{/vagrant/supplier/vendor/cakephp/cakephp/src/Console/Shell.php:456}() /vagrant/supplier/vendor/cakephp/cakephp/src/Console/Shell.php:456
PHP   8. Bake\Shell\Task\ModelTask->main() /vagrant/supplier/vendor/cakephp/cakephp/src/Console/Shell.php:456
PHP   9. Bake\Shell\Task\ModelTask->bake() /vagrant/supplier/vendor/cakephp/bake/src/Shell/Task/ModelTask.php:96
PHP  10. Bake\Shell\Task\ModelTask->getTableContext() /vagrant/supplier/vendor/cakephp/bake/src/Shell/Task/ModelTask.php:109
PHP  11. Bake\Shell\Task\ModelTask->getAssociations() /vagrant/supplier/vendor/cakephp/bake/src/Shell/Task/ModelTask.php:124
PHP  12. Bake\Shell\Task\ModelTask->findHasMany() /vagrant/supplier/vendor/cakephp/bake/src/Shell/Task/ModelTask.php:216
PHP  13. Bake\Shell\Task\ModelTask->getTableObject() /vagrant/supplier/vendor/cakephp/bake/src/Shell/Task/ModelTask.php:336
PHP  14. Cake\ORM\TableRegistry::get() /vagrant/supplier/vendor/cakephp/bake/src/Shell/Task/ModelTask.php:182
PHP  15. Cake\ORM\Locator\TableLocator->get() /vagrant/supplier/vendor/cakephp/cakephp/src/ORM/TableRegistry.php:111
PHP  16. Cake\ORM\Locator\TableLocator->_create() /vagrant/supplier/vendor/cakephp/cakephp/src/ORM/Locator/TableLocator.php:175
PHP  17. Cake\ORM\Table->__construct() /vagrant/supplier/vendor/cakephp/cakephp/src/ORM/Locator/TableLocator.php:207
PHP  18. App\Model\Table\ProductsTable->initialize() /vagrant/supplier/vendor/cakephp/cakephp/src/ORM/Table.php:288
PHP  19. Cake\ORM\Table->addBehavior() /vagrant/supplier/src/Model/Table/ProductsTable.php:54
PHP  20. Cake\Core\ObjectRegistry->load() /vagrant/supplier/vendor/cakephp/cakephp/src/ORM/Table.php:603
PHP  21. Cake\ORM\BehaviorRegistry->_create() /vagrant/supplier/vendor/cakephp/cakephp/src/Core/ObjectRegistry.php:93
PHP  22. Tools\Model\Behavior\SluggedBehavior->__construct() /vagrant/supplier/vendor/cakephp/cakephp/src/ORM/BehaviorRegistry.php:129
PHP  23. Cake\ORM\Behavior->__construct() /vagrant/supplier/vendor/dereuromark/cakephp-tools/src/Model/Behavior/SluggedBehavior.php:100
PHP  24. Tools\Model\Behavior\SluggedBehavior->initialize() /vagrant/supplier/vendor/cakephp/cakephp/src/ORM/Behavior.php:166
```

**Comment by dereuromark** [comment]
Does https://github.com/dereuromark/cakephp-tools/blob/master/src/Model/Behavior/SluggedBehavior.php fix it?
I guess there was no test case for those code paths yet.

**Comment by TamiasSibiricus** [comment]
Maybe this is bug from bake plugin. Cause when i remove SluggedBehavior from app Products table file baking was completed.

**Comment by dereuromark** [comment]
Either way the missing class causes this, I can tag a new bugfix release once you confirmed that it now works.

**Comment by TamiasSibiricus** [comment]
Another problem
```
Exception: Table "App\Model\Table\ProductsTable" is not associated with "name" in [/vagrant/supplier/vendor/cakephp/cakephp/src/ORM/Table.php, line 1882]
2016-04-05 13:32:46 Error: [RuntimeException] Table "App\Model\Table\ProductsTable" is not associated with "name"
Stack Trace:
#0 /vagrant/supplier/vendor/dereuromark/cakephp-tools/src/Model/Behavior/SluggedBehavior.php(134): Cake\ORM\Table->__get('name')
#1 /vagrant/supplier/vendor/cakephp/cakephp/src/ORM/Behavior.php(166): Tools\Model\Behavior\SluggedBehavior->initialize(Array)
#2 /vagrant/supplier/vendor/dereuromark/cakephp-tools/src/Model/Behavior/SluggedBehavior.php(101): Cake\ORM\Behavior->__construct(Object(App\Model\Table\ProductsTable), Array)
#3 /vagrant/supplier/vendor/cakephp/cakephp/src/ORM/BehaviorRegistry.php(129): Tools\Model\Behavior\SluggedBehavior->__construct(Object(App\Model\Table\ProductsTable), Array)
#4 /vagrant/supplier/vendor/cakephp/cakephp/src/Core/ObjectRegistry.php(93): Cake\ORM\BehaviorRegistry->_create('Tools\\Model\\Beh...', 'Slugged', Array)
#5 /vagrant/supplier/vendor/cakephp/cakephp/src/ORM/Table.php(603): Cake\Core\ObjectRegistry->load('Tools.Slugged', Array)
#6 /vagrant/supplier/src/Model/Table/ProductsTable.php(54): Cake\ORM\Table->addBehavior('Tools.Slugged', Array)
#7 /vagrant/supplier/vendor/cakephp/cakephp/src/ORM/Table.php(288): App\Model\Table\ProductsTable->initialize(Array)
#8 /vagrant/supplier/vendor/cakephp/cakephp/src/ORM/Locator/TableLocator.php(207): Cake\ORM\Table->__construct(Array)
#9 /vagrant/supplier/vendor/cakephp/cakephp/src/ORM/Locator/TableLocator.php(175): Cake\ORM\Locator\TableLocator->_create(Array)
#10 /vagrant/supplier/vendor/cakephp/cakephp/src/ORM/TableRegistry.php(111): Cake\ORM\Locator\TableLocator->get('Products', Array)
#11 /vagrant/supplier/vendor/cakephp/bake/src/Shell/Task/ModelTask.php(182): Cake\ORM\TableRegistry::get('Products', Array)
#12 /vagrant/supplier/vendor/cakephp/bake/src/Shell/Task/ModelTask.php(336): Bake\Shell\Task\ModelTask->getTableObject('Products', 'products')
#13 /vagrant/supplier/vendor/cakephp/bake/src/Shell/Task/ModelTask.php(216): Bake\Shell\Task\ModelTask->findHasMany(Object(App\Model\Table\TagsTable), Array)
#14 /vagrant/supplier/vendor/cakephp/bake/src/Shell/Task/ModelTask.php(124): Bake\Shell\Task\ModelTask->getAssociations(Object(App\Model\Table\TagsTable))
#15 /vagrant/supplier/vendor/cakephp/bake/src/Shell/Task/ModelTask.php(109): Bake\Shell\Task\ModelTask->getTableContext(Object(App\Model\Table\TagsTable), 'tags', 'Tags')
#16 /vagrant/supplier/vendor/cakephp/bake/src/Shell/Task/ModelTask.php(96): Bake\Shell\Task\ModelTask->bake('Tags')
#17 [internal function]: Bake\Shell\Task\ModelTask->main('Tags')
#18 /vagrant/supplier/vendor/cakephp/cakephp/src/Console/Shell.php(456): call_user_func_array(Array, Array)
#19 /vagrant/supplier/vendor/cakephp/cakephp/src/Console/Shell.php(450): Cake\Console\Shell->runCommand(Array, false)
#20 /vagrant/supplier/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(217): Cake\Console\Shell->runCommand(Array, true, Array)
#21 /vagrant/supplier/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(181): Cake\Console\ShellDispatcher->_dispatch(Array)
#22 /vagrant/supplier/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(127): Cake\Console\ShellDispatcher->dispatch(Array)
#23 /vagrant/supplier/bin/cake.php(33): Cake\Console\ShellDispatcher::run(Array)
#24 {main}
```
My plugin use another connection and get data from another database
there is present products and tags tables in both databases but with different schema
As i said previously bake command seems completely ignore connections option and try to load app 'Products' table instead plugin 'MyPlugin.Products' table(which not contain 'title' field). When i comment out behavior addition all works ok.
This is app Products table:
```
class ProductsTable extends Table
{
    public function initialize(array $config)
    {
        ....
        $this->addBehavior('Tools.Slugged', [
            'label' => 'title',
			'length' => 255,
			'unique' => true,
			'case' => 'low',
		]);
    }
}
```
I understand that is mostly bake plugin problem
But when i baking models i think bake proces should serch tables in plugin and then at app to prevent same naming crossing.

**Comment by TamiasSibiricus** [comment]
So your patch works well but not completely in my situation.

**Comment by dereuromark** [comment]
Any feedback? Are you able to provide a PR?

**Comment by TamiasSibiricus** [comment]
Right now i can't proof or decline that is work well, cause this project frozen by customer for long time. if you can wait 1 week i can try to reproduce it at vanilla setup with same situation. Should i do that?
